import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { TanStackRouterVite } from '@tanstack/router-vite-plugin'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react({
      // Disable type checking during build - the route tree will be generated by TanStack Router plugin
      typescript: {
        ignoreBuildErrors: true,
      },
    }),
    TanStackRouterVite(),
  ],
  base: process.env.GITHUB_PAGES === 'true' ? '/Recap/' : '/',
  build: {
    outDir: 'dist',
  },
})
